# Generated by Django 4.0.6 on 2022-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
