# Generated by Django 4.0.6 on 2022-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0002_alter_login_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='login_id',
        ),
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
