# Generated by Django 4.0.6 on 2022-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0003_remove_login_login_id_login_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
