# Generated by Django 4.0.6 on 2022-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('HomeId', models.AutoField(primary_key=True, serialize=False)),
                ('HomeName', models.CharField(max_length=50)),
                ('HomeCat', models.CharField(max_length=30)),
                ('HomePrice', models.IntegerField()),
                ('HomeImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
