# Generated by Django 4.0.6 on 2022-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0006_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='HomeImage',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
