# Generated by Django 4.0.6 on 2022-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0008_alter_home_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('HomeName', models.CharField(max_length=50)),
            ],
        ),
    ]
