# Generated by Django 4.0.6 on 2022-09-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0009_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='HomeName',
            new_name='homename',
        ),
    ]
